swagger: '2.0'
x-stoplight:
  id: 0b0a8c42aef56
info:
  version: 1.1.3
  title: GATEWAY STATUS
  description: |
    ## Using the API

    To use the API you must ask for your Kushki Sandbox, composed of a `Public-Merchant-Id` and a `Private-Merchant-Id`.

    * The current version of the Kushki API rests at: `https://api.kushkipagos.com/`
    * The testing version rests at: `https://api-uat.kushkipagos.com/`


    ## Endpoints

    We dispose various endpoints to start your payment flows, find our products available:

    * [Get gateway status](https://api-docs.kushkipagos.com/docs/online-payments/gateway-status/operations/get-a-rule-v-1-gateway-status)

    [Return Home](/)

    > Got a suggestion on this documentation? [Contact Us.](mailto:techwriting@kushki.com)
host: api-uat.kushkipagos.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    scopes: {}
    authorizationUrl: ''
paths:
  /rules/v1/gatewayStatus:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              card:
                type: boolean
              transfer:
                type: boolean
              cash:
                type: boolean
      summary: Get gateway status
      operationId: gatewaySatus0
      parameters:
        - in: header
          name: Public-key
          type: string
          required: true
        - type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
      description: |-
        Request the status of all the payment methods configured for a specific merchant.

        <!-- theme: warning -->
        > #### Service available in the following countries:
        >
        > Ecuador, Chile, Colombia, México, Perú.  
        > Check out our full [list of services by country](https://api-docs.kushkipagos.com/docs/online-payments/services-by-country)

        > Got a suggestion on this documentation? [Contact Us.](mailto:techwriting@kushki.com)
      x-stoplight:
        id: mlih0pkwebjjb
responses:
  'trait:invalidBin:402':
    description: Invalid Bin
    schema:
      $ref: '#/definitions/InvalidBinResponse'
  'trait:badRequest:400':
    description: Bad Request
    schema:
      $ref: '#/definitions/BadRequestResponse'
  'trait:fetchedList:200':
    description: Fetch a transactions list
    schema:
      type: object
      required:
        - has_more
        - data
      properties:
        has_more:
          type: boolean
          example: true
        data:
          type: array
          items:
            required:
              - subtotalIVA0
              - date
              - lastFourDigitsOfCard
              - transactionStatus
              - transactionId
              - voidedBy
              - merchantName
              - cardHolderName
              - approvedTransactionAmount
              - numberOfMonths
              - extraTaxes
              - saleTicketNumber
              - ivaValue
              - isDeferred
              - ticketNumber
              - id
              - dateAndTimeTransaction
              - cardType
              - subtotalIVA
              - requestAmount
              - currencyCode
              - transactionType
              - processorName
              - iceValue
              - merchantId
              - processorBankName
              - approvalCode
            properties:
              subtotalIVA0:
                type: number
                example: 10
              date:
                type: string
                example: '2017-03-24T18:52:34.000Z'
              lastFourDigitsOfCard:
                type: string
                example: 1234
              transactionStatus:
                type: string
                example: APPROVAL
              transactionId:
                type: string
                example: 1234567890987654
              voidedBy:
                type: string
                example: 10334120439012934
              merchantName:
                type: string
                example: Some_Merchant_Name
              cardHolderName:
                type: string
                example: John Doe
              approvedTransactionAmount:
                type: string
                example: 135.5
              numberOfMonths:
                type: string
                example: 0
              ExtraTaxes:
                type: array
                items:
                  required:
                    - tasaAeroportuaria
                    - agenciaDeViaje
                    - iac
                  properties:
                    tasaAeroportuaria:
                      type: object
                      properties:
                        taxid:
                          type: string
                          example: '4'
                        taxAmount:
                          type: string
                          example: 2
                        taxName:
                          type: string
                          example: TASA_AERO
                    iac:
                      type: object
                      properties:
                        taxid:
                          type: string
                          example: '5'
                        taxAmount:
                          type: string
                          example: 2
                        taxName:
                          type: string
                          example: IAC
                    agenciaDeViaje:
                      type: object
                      properties:
                        taxid:
                          type: string
                          example: '6'
                        taxAmount:
                          type: string
                          example: 2
                        taxName:
                          type: string
                          example: TASA_ADMIN_AGEN_COD
              saleTicketNumber:
                type: string
                example: 1204493249523
              ivaValue:
                type: integer
                example: 15.5
              isDeferred:
                type: string
                example: 'Y'
              ticketNumber:
                type: string
                example: 1234567890987654
              id:
                type: string
                example: '123456'
              dateAndTimeTransaction:
                type: string
                example: 12345012469
              cardType:
                type: string
                example: Master Card
              subtotalIVA:
                type: number
                example: 10
              requestAmount:
                type: string
                example: 130
              currencyCode:
                type: string
                example: USD
              transactionType:
                type: string
                example: SALE
              processorName:
                type: string
                example: Some_Processor_Name
              iceValue:
                type: number
                example: 10
              merchantId:
                type: string
                example: 1200000432450023
              processorBankName:
                type: string
                example: Some_Bank_Name
              approvalCode:
                type: string
                example: 342347
              Metadata:
                type: object
                properties:
                  key1:
                    type: string
                    example: value1
              subscription_metadata:
                type: object
                properties:
                  key2:
                    type: string
                    example: value2
    examples:
      example-1:
        has_more: true
        data:
          - subtotalIVA0: 10
            date: '2017-03-24T18:52:34.000Z'
            lastFourDigitsOfCard: 1234
            transactionStatus: APPROVAL
            transactionId: 1234567890987654
            voidedBy: 10334120439012934
            merchantName: Some_Merchant_Name
            cardHolderName: John Doe
            approvedTransactionAmount: 135.5
            numberOfMonths: 0
            ExtraTaxes:
              - tasaAeroportuaria:
                  taxid: '4'
                  taxAmount: 2
                  taxName: TASA_AERO
                iac:
                  taxid: '5'
                  taxAmount: 2
                  taxName: IAC
                agenciaDeViaje:
                  taxid: '6'
                  taxAmount: 2
                  taxName: TASA_ADMIN_AGEN_COD
            saleTicketNumber: 1204493249523
            ivaValue: 15.5
            isDeferred: 'Y'
            ticketNumber: 1234567890987654
            id: '123456'
            dateAndTimeTransaction: 12345012469
            cardType: Master Card
            subtotalIVA: 10
            requestAmount: 130
            currencyCode: USD
            transactionType: SALE
            processorName: Some_Processor_Name
            iceValue: 10
            merchantId: 1200000432450023
            processorBankName: Some_Bank_Name
            approvalCode: 342347
            Metadata:
              key1: value1
            subscription_metadata:
              key2: value2
  'trait:created:201':
    description: Created
    schema:
      type: object
      required:
        - ticketNumber
      properties:
        ticketNumber:
          type: string
          example: '123456789012345678'
    examples:
      example-1:
        ticketNumber: '123456789012345678'
  'trait:unexpectedError:500':
    description: Unexpected Error
    schema:
      $ref: '#/definitions/UnexpectedErrorResponse'
  'trait:tokenCreated:201':
    description: TokenCreated
    schema:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          example: AbCDef123456Z7Ghi8901234jkLMNopQ
definitions: {}
